### ISSUE TITLE
Fix house maps

### ISSUE THREAD

**Issue by fredriksiemund** [careerfairsystems/arkad-app-2018#135]
Fix house maps for MA, they have changed.

**Comment by tovesson** [comment]
Talking to Simon to see if we can make it more clear somehow.

**Comment by tovesson** [comment]
Simon added some shadow under the buildings, I think it makes it more clear: https://drive.google.com/drive/folders/1f1dlNmA0BMBvqo5pwT-XrfjSXIUh-J-2
