### ISSUE TITLE
Check if font awesome could be used

### ISSUE THREAD

**Issue by tovesson** [careerfairsystems/arkad-app-2018#21]
Read about font awesome and see if it meets our requirements.
A library using Font Awesome can be found here: https://github.com/entria/react-native-fontawesome
A library with it included along with other font libraries can be found here: https://github.com/oblador/react-native-vector-icons
Read about them an see which one is preferred.

**Comment by liljagustav** [comment]
**Ikoner**

**Map**
map-o - ej ifylld karta
map - ifylld

**Events**
Calendar-check-o - Kalender med ett check tecken
Calendar-o - Kalender som är tom (kanske fungerar som alternativ)

**Companies**
Briefcase

**Other**
filter - För filter
question - frågetecken för FAQ
heart - Hjärta ifyllt
heart-o - Hjärta borders
